### ISSUE TITLE
First Android App codelab:  cannot resolve symbol FirstFragmentDirections  [Solved]

### ISSUE THREAD

**Issue by haneefputtur** [google-developer-training/first-android-app#43]
**Describe the problem**

 view.findViewById(R.id.random_button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView showCountTextView = view.getRootView().findViewById(R.id.textview_first);
                int currentCount = Integer.parseInt(showCountTextView.getText().toString());

               FirstFragmentDirections.ActionFirstFragmentToSecondFragment action =
                        FirstFragmentDirections.
                                actionFirstFragmentToSecondFragment(currentCount);
                NavHostFragment.findNavController(FirstFragment.this)
                        .navigate(action);
            }
        });

I get error which says cannot resolve symbol FirstFragmentDirections

**In which step of the codelab can this issue be found?**
Step number. 6

**Versions**
1. What version of Android Studio are you using? : 3.6.2
2. What API level are you targeting? 28

**Comment by haneefputtur** [comment]
Solved as follows

build.gradle project level added below line in dependency

  classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.0.0"

build.gradle module /app  added below line in dependency

apply plugin: "androidx.navigation.safeargs"

Then Click Sync

Rebuild Project

**Comment by bass212drum** [comment]
Follow Step 6: Create the argument for the navigation action 
Step 6 "In the navigation graph"  = nav_graph.xml, do the operation like "Add Argument dialog" in nav_graph.xml , not in SecondFragment.kt   
If you Add Argument dialog right, you won't have "Too many arguments" problem.

The text is NOT clear, I made the same mistake like you did. I try to find  "Add Argument dialog"  first in "SecondFragment.kt" since the text said "Click on SecondFragment" but I can't find  "Add Argument dialog"  , then I look at " fragment_second.xml" then " FirstFragment.kt" then "fragment_first.xml" then I asked a person who knows kotlin and he didn't know why there was this "Too many arguments" problem.

This problem took me a week to solve by myself and people can call me stupid since the text saide "In the navigation graph" but for a total beginner, it is better off the professional who wrote this task can write it more clearly. "In the nav_graph.xml" is more clear than  "In the navigation graph".

Hopefull this will help you.
